title: haiwei hu
email: hhu8@tulane.edu
description: >-
  Linguistics PhD student with a background in computer science, economics, and statistics. 
  Interested in low-resource NLP; morphology, semantics, & syntax; language documentation and revitalisation; 
  and speech community-centered language technologies. Student of Kaqchikel, K'iche', and Maaya T'aan.

url: "https://huhaiwei.github.io"
baseurl: ""
lang: en
keywords: computational-linguistics, mayan, k'iche', kaqchikel

# markdown/build settings
markdown: kramdown
permalink: /:title/

# turn off jekyll defaults we don't need for a minimal site
theme: null
plugins: []

# includes & excludes
include: ["_pages"]
exclude:
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor
